import type { GovDataset } from '../types/observation'

export const GOV_DATASETS: GovDataset[] = [
  {
    id: 'dgca-pax',
    source: 'DGCA Monthly Passenger Statistics',
    organization: 'Directorate General of Civil Aviation',
    access_type: 'PUBLIC',
    api_key_required: false,
    format: 'HTML',
    status: 'CONNECTED',
    last_retrieved: '2026-09-20T10:15:00Z',
    last_attempt: '2026-09-21T06:00:00Z',
    record_count: 1480,
    checksum: 'sha256-a982f1b0',
    reference_period: 'Jan 2024 - Aug 2026',
    source_url: 'https://dgca.gov.in/digigov-portal/?page=statisticsMenu/airTransportStatistics/monthlystatistics/monthlypassengerstatistics.html',
    update_frequency: 'Monthly',
    data_origin: 'OFFICIAL',
  },
  {
    id: 'dgca-circulars',
    source: 'DGCA Office Circulars & Air Tariff Guidelines',
    organization: 'Directorate General of Civil Aviation',
    access_type: 'PUBLIC',
    api_key_required: false,
    format: 'HTML',
    status: 'CONNECTED',
    last_retrieved: '2026-09-21T04:30:00Z',
    last_attempt: '2026-09-21T08:00:00Z',
    record_count: 48,
    checksum: 'sha256-78cc12d8',
    reference_period: 'Current 2026 Directives',
    source_url: 'https://dgca.gov.in/digigov-portal/?page=newsdetail/officecircular/officecircular.html',
    update_frequency: 'As published',
    data_origin: 'OFFICIAL',
  },
  {
    id: 'mospi-esankhyiki',
    source: 'MoSPI Consumer Price Index (Transport & Aviation)',
    organization: 'Ministry of Statistics and Programme Implementation',
    access_type: 'PUBLIC',
    api_key_required: false,
    format: 'JSON',
    status: 'CONNECTED',
    last_retrieved: '2026-09-18T14:20:00Z',
    last_attempt: '2026-09-21T07:15:00Z',
    record_count: 176,
    checksum: 'sha256-f831ab90',
    reference_period: 'Base 2012=100 (2020-2026)',
    source_url: 'https://api.mospi.gov.in/api/cpi/getCPIData',
    update_frequency: 'Monthly',
    data_origin: 'OFFICIAL',
  },
  {
    id: 'data-gov-in',
    source: 'Open Government Aviation Route Registry',
    organization: 'data.gov.in',
    access_type: 'PUBLIC',
    api_key_required: false,
    format: 'JSON',
    status: 'CONNECTED',
    last_retrieved: '2026-09-15T09:00:00Z',
    last_attempt: '2026-09-21T09:00:00Z',
    record_count: 480,
    checksum: 'sha256-b749d21c',
    reference_period: 'Domestic Network 2026',
    source_url: 'https://data.gov.in',
    update_frequency: 'Annual',
    data_origin: 'OFFICIAL',
  },
]
