import { useEffect, useMemo, useState } from 'react'
import { Building2, MapPin, Plane, RefreshCw, Search, type LucideIcon } from 'lucide-react'
import { fetchAllCorridorFlights, type LiveFlight } from '../services/flightData'
import { radarAirports } from '../services/aviationRadar'

type Airport = { code:string; city:string; movements:number; airlines:number; arrivals:number; departures:number }

export default function AviationAirports() {
  const [flights,setFlights]=useState<LiveFlight[]>([]); const [loading,setLoading]=useState(true); const [query,setQuery]=useState(''); const [selected,setSelected]=useState<string|null>(null)
  async function load(){setLoading(true);try{const rows=(await fetchAllCorridorFlights()).flatMap(r=>r.flights);setFlights(rows)}finally{setLoading(false)}}
  useEffect(()=>{void load()},[])
  const airports=useMemo(()=>{const map=new Map<string,Airport>(); const add=(code:string,city:string,kind:'arrivals'|'departures',f:LiveFlight)=>{if(!code)return;const a=map.get(code)??{code,city:city||'City unavailable',movements:0,airlines:0,arrivals:0,departures:0};a.movements++;a[kind]++;map.set(code,a)};flights.forEach(f=>{if(f.dep_iata!=='LIVE'&&f.dep_iata!=='TRACK') add(f.dep_iata,f.dep_city,'departures',f); if(f.arr_iata!=='LIVE'&&f.arr_iata!=='TRACK') add(f.arr_iata,f.arr_city,'arrivals',f); if(f.latitude!=null&&f.longitude!=null){const nearest=radarAirports.reduce((best,a)=>Math.hypot(a.lat-f.latitude!,a.lng-f.longitude!)<Math.hypot(best.lat-f.latitude!,best.lng-f.longitude!)?a:best,radarAirports[0]); add(nearest.code,nearest.name,'arrivals',f)}});return [...map.values()].map(a=>({...a,airlines:new Set(flights.filter(f=>f.airline_name&&((f.dep_iata===a.code)||(f.arr_iata===a.code))).map(f=>f.airline_name)).size})).sort((a,b)=>b.movements-a.movements)},[flights])
  const visible=airports.filter(a=>`${a.code} ${a.city}`.toLowerCase().includes(query.toLowerCase())); const active=visible.find(a=>a.code===selected)??visible[0]
  const metricCards: Array<[string, number, LucideIcon]> = active ? [['Movements',active.movements,Plane],['Departures',active.departures,MapPin],['Arrivals',active.arrivals,Building2]] : []
  return <div style={{maxWidth:1280,margin:'0 auto',display:'grid',gap:14}}>
    <section style={{padding:'20px 22px',borderRadius:14,background:'linear-gradient(110deg,#06326c,#0d6bb4)',color:'#fff',display:'flex',justifyContent:'space-between',gap:16,alignItems:'center',flexWrap:'wrap'}}><div><div style={{fontSize:10,fontWeight:800,letterSpacing:'.12em',color:'#a7ddff'}}>AVIATION INTELLIGENCE</div><h1 style={{margin:'5px 0',fontSize:26,letterSpacing:'-.03em'}}>Airport operations</h1><p style={{margin:0,fontSize:12,color:'#c8e6ff'}}>Airports observed in the current connected flight-provider response.</p></div><button onClick={()=>void load()} style={{display:'flex',alignItems:'center',gap:7,border:'1px solid #84c8f3',borderRadius:8,padding:'8px 11px',background:'#ffffff1c',color:'#fff',fontWeight:700,cursor:'pointer'}}><RefreshCw size={14} style={{animation:loading?'spin 1s linear infinite':'none'}}/> Refresh</button></section>
    <section style={{display:'grid',gridTemplateColumns:'minmax(300px,.7fr) minmax(400px,1.3fr)',gap:14}} className="aviation-airports-grid"><div style={{border:'1px solid var(--color-border-primary)',borderRadius:14,background:'var(--color-surface-bg)',overflow:'hidden'}}><div style={{padding:14,borderBottom:'1px solid var(--color-border-primary)'}}><div style={{display:'flex',justifyContent:'space-between'}}><b style={{color:'var(--color-text-primary)'}}>Observed airports</b><span style={{fontSize:10,color:'var(--color-text-tertiary)'}}>{visible.length} returned</span></div><div style={{marginTop:11,display:'flex',gap:7,alignItems:'center',padding:'8px 9px',borderRadius:8,background:'var(--color-surface-secondary)'}}><Search size={13} color="var(--color-text-tertiary)"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search IATA or city…" style={{border:0,outline:0,background:'transparent',width:'100%',fontSize:12,color:'var(--color-text-primary)'}}/></div></div><div style={{maxHeight:520,overflowY:'auto'}}>{visible.length?visible.map(a=><button key={a.code} onClick={()=>setSelected(a.code)} style={{display:'flex',width:'100%',padding:'13px 14px',gap:10,textAlign:'left',cursor:'pointer',border:0,borderBottom:'1px solid var(--color-border-primary)',background:active?.code===a.code?'var(--color-surface-secondary)':'transparent'}}><div style={{width:35,height:35,display:'grid',placeItems:'center',borderRadius:9,background:'#1769e817',color:'#1769e8',fontWeight:800,fontFamily:'var(--font-mono)',fontSize:11}}>{a.code}</div><div style={{flex:1}}><b style={{fontSize:12,color:'var(--color-text-primary)'}}>{a.city}</b><div style={{fontSize:10,color:'var(--color-text-tertiary)',marginTop:3}}>{a.movements} observed movements</div></div><span style={{fontSize:10,color:'#1687e8',fontWeight:700}}>{a.airlines} carriers</span></button>):<div style={{padding:28,textAlign:'center',fontSize:12,color:'var(--color-text-secondary)'}}>No airport rows are available from the connected provider.</div>}</div></div>
    <div style={{padding:22,border:'1px solid var(--color-border-primary)',borderRadius:14,background:'var(--color-surface-bg)'}}>{active?<><div style={{display:'flex',justifyContent:'space-between',gap:10,alignItems:'flex-start'}}><div style={{display:'flex',gap:11,alignItems:'center'}}><div style={{width:46,height:46,borderRadius:12,display:'grid',placeItems:'center',background:'#1769e817',color:'#1769e8'}}><Building2 size={22}/></div><div><div style={{fontSize:24,fontWeight:850,color:'var(--color-text-primary)',fontFamily:'var(--font-mono)'}}>{active.code}</div><div style={{fontSize:12,color:'var(--color-text-secondary)'}}>{active.city}</div></div></div><span style={{fontSize:10,color:'#1687e8',fontWeight:800,padding:'5px 8px',borderRadius:99,background:'#1769e814'}}>LIVE OBSERVED</span></div><div style={{display:'grid',gridTemplateColumns:'repeat(3,minmax(0,1fr))',gap:12,marginTop:22}}>{metricCards.map(([label,value,Icon])=><div key={label} style={{padding:14,borderRadius:10,background:'var(--color-surface-secondary)'}}><Icon size={15} color="#1769e8"/><div style={{fontSize:23,fontWeight:800,color:'var(--color-text-primary)',marginTop:10}}>{value}</div><div style={{fontSize:10,color:'var(--color-text-tertiary)'}}>{label}</div></div>)}</div><div style={{marginTop:18,padding:14,borderRadius:10,background:'var(--color-surface-secondary)',fontSize:12,lineHeight:1.55,color:'var(--color-text-secondary)'}}>This view reports only airports present in the current flight feed. Passenger volumes, annual ranks, and route totals are intentionally not estimated without a connected official airport-data source.</div></>:<div style={{padding:50,textAlign:'center',color:'var(--color-text-secondary)'}}>Select an airport to view live observed activity.</div>}</div></section>
  </div>
}
